version: 0.0
os: linux 
files:
  - source: /
    destination: /home/ubuntu/visor
# permissions:
#   - object: /
#       pattern: "**"
#       owner: ec2-user
#       group: ec2-user    
hooks:
  BeforeInstall:
    - location: scripts/preinstall_server.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ubuntu          