image: python:3.7.2
pipelines:
  default:
    - step:
        script:
          - pip install -r requirements.txt
          - apt-get update # required to install zip
          - apt-get install -y zip # required for packaging up the application
          - zip -r /tmp/artifact.zip * # package up the application for deployment
          - python codedeploy_deploy.py # run the deployment script
         
    
